import React, { useEffect, useState } from 'react';
import { dotaService } from '../services/dotaService';
import { OpenDotaHero, ProMatchItem, ProPlayerItem, PageRoute } from '../types';
import { ErrorMessage } from '../components/common/ErrorMessage';

interface Props { onNavigate:(p:PageRoute)=>void; onSelectPlayer:(id:number)=>void; onSelectHero:(id:number)=>void; onSelectMatch:(id:number|string)=>void; onOpenStream:()=>void; }
export const HomePage: React.FC<Props> = ({onNavigate,onSelectPlayer,onSelectHero,onSelectMatch}) => {
 const [heroes,setHeroes]=useState<OpenDotaHero[]>([]); const [matches,setMatches]=useState<ProMatchItem[]>([]); const [players,setPlayers]=useState<ProPlayerItem[]>([]); const [error,setError]=useState('');
 useEffect(()=>{Promise.all([dotaService.getHeroStats(),dotaService.getProMatches(),dotaService.getProPlayers()]).then(([h,m,p])=>{setHeroes(h);setMatches(m);setPlayers(p);}).catch(e=>setError(e instanceof Error?e.message:'Data request failed'));},[]);
 if(error) return <ErrorMessage message={error} onRetry={()=>location.reload()} />;
 const meta=[...heroes].filter(h=>(h.pro_pick||0)>0).sort((a,b)=>(b.pro_win||0)/(b.pro_pick||1)-(a.pro_win||0)/(a.pro_pick||1)).slice(0,8);
 return <div className="max-w-[1400px] mx-auto px-4 lg:px-8 py-8 space-y-8">
  <section><div className="text-[11px] font-mono uppercase tracking-widest text-[#89ceff] mb-2">Real Dota 2 analytics</div><h1 className="text-4xl md:text-6xl font-black text-white">AegisBuff</h1><p className="text-white/50 mt-2 max-w-2xl">Post-match and professional data fetched through the AegisBuff API from OpenDota. No simulated players, matches or patch statistics.</p></section>
  <div className="grid md:grid-cols-3 gap-4"><div className="p-5 rounded-2xl bg-[#15161a] border border-white/10"><div className="text-white/40 text-xs uppercase">Heroes</div><div className="text-3xl font-black text-white mt-1">{heroes.length}</div></div><div className="p-5 rounded-2xl bg-[#15161a] border border-white/10"><div className="text-white/40 text-xs uppercase">Pro players returned</div><div className="text-3xl font-black text-white mt-1">{players.length}</div></div><div className="p-5 rounded-2xl bg-[#15161a] border border-white/10"><div className="text-white/40 text-xs uppercase">Recent pro matches</div><div className="text-3xl font-black text-white mt-1">{matches.length}</div></div></div>
  <div className="grid lg:grid-cols-2 gap-6"><section className="p-5 rounded-2xl bg-[#15161a] border border-white/10"><h2 className="text-lg font-bold text-white mb-4">Recent professional matches</h2>{matches.slice(0,8).map(m=><button key={m.match_id} onClick={()=>onSelectMatch(m.match_id)} className="w-full flex justify-between gap-3 p-3 rounded-xl hover:bg-white/5 text-left"><div><div className="text-white font-semibold">{m.radiant_name} vs {m.dire_name}</div><div className="text-xs text-white/40">{m.league_name} · #{m.match_id}</div></div><div className="font-mono text-white/80">{m.radiant_score}:{m.dire_score}</div></button>)}</section>
  <section className="p-5 rounded-2xl bg-[#15161a] border border-white/10"><h2 className="text-lg font-bold text-white mb-4">Professional hero sample</h2>{meta.map(h=><button key={h.id} onClick={()=>onSelectHero(h.id)} className="w-full flex items-center gap-3 p-2 rounded-xl hover:bg-white/5 text-left"><img src={h.img} className="w-10 h-10 rounded"/><div className="flex-1"><div className="text-white font-semibold">{h.localized_name}</div><div className="text-xs text-white/40">{h.pro_pick} picks · {h.pro_win} wins</div></div><span className="font-mono text-[#89ceff]">{(((h.pro_win||0)/Math.max(1,h.pro_pick||0))*100).toFixed(1)}%</span></button>)}</section></div>
  <div className="flex flex-wrap gap-3"><button onClick={()=>onNavigate('heroes')} className="px-4 py-2 rounded-xl bg-[#ff525b] text-white font-bold">Browse heroes</button><button onClick={()=>onNavigate('rankings')} className="px-4 py-2 rounded-xl bg-white/5 text-white/70">Pro players</button><button onClick={()=>onNavigate('ai-coach')} className="px-4 py-2 rounded-xl bg-white/5 text-white/70">AI Coach</button></div>
 </div>;
};
